from enum import Enum


class Building(Enum):
    WHEAT_FIELD = 1
    APPLE_ORCHARD = 2
    RANCH = 3
    FOREST = 4
    MINE = 5
    FRUIT_AND_VEGETABLE_MARKET = 6
    CHEESE_FACTORY = 7
    FURNITURE_FACTORY = 8
    BAKERY = 9
    CONVENIENCE_STORE = 10
    CAFE = 11
    FAMILY_RESTAURANT = 12
    FLOWER_GARDEN = 13
    MACKEREL_BOAT = 14
    TUNA_BOAT = 15
    FLOWER_SHOP = 16
    FOOD_WAREHOUSE = 17
    SUSHI_BAR = 18
    PIZZA_JOINT = 19
    HAMBURGER_STAND = 20
    PUBLISHER = 21
    TAX_OFFICE = 22
    HARBOR = 23
    STADIUM = 24
    TV_STATION = 25
    BUSINESS_CENTER = 26
    SHOPPING_MALL = 27
    AMUSEMENT_PARK = 28
    RADIO_TOWER = 29
    AIRPORT = 30
    TRAIN_STATION = 31
